/// Categorized types of coach messages.
enum CoachMessageType {
  /// Celebration of daily/mission milestones.
  achievement,

  /// Warning regarding repeated postponements or overloading.
  warning,

  /// Guidance when recovery plan is generated or applied.
  recovery,

  /// Recognition of increased completion vs previous days.
  improvement,

  /// Observation on realistic daily workload & planning.
  planning,
}

/// Fact-based message generated by the Coach Engine.
class CoachMessage {
  final String id;
  final CoachMessageType type;
  final String title;
  final String body;
  final String actionRecommendation;
  final DateTime timestamp;
  final Map<String, dynamic> evidence;

  const CoachMessage({
    required this.id,
    required this.type,
    required this.title,
    required this.body,
    required this.actionRecommendation,
    required this.timestamp,
    this.evidence = const {},
  });

  Map<String, dynamic> toJson() => {
        'id': id,
        'type': type.name,
        'title': title,
        'body': body,
        'actionRecommendation': actionRecommendation,
        'timestamp': timestamp.toIso8601String(),
        'evidence': evidence,
      };

  factory CoachMessage.fromJson(Map<String, dynamic> json) => CoachMessage(
        id: json['id'] as String,
        type: CoachMessageType.values.firstWhere(
          (e) => e.name == json['type'],
          orElse: () => CoachMessageType.planning,
        ),
        title: json['title'] as String? ?? 'Coach Observation',
        body: json['body'] as String? ?? '',
        actionRecommendation: json['actionRecommendation'] as String? ?? '',
        timestamp: DateTime.tryParse(json['timestamp'] as String? ?? '') ??
            DateTime.now(),
        evidence: json['evidence'] as Map<String, dynamic>? ?? const {},
      );
}
