import 'planner_entry.dart';

/// Action suggested by the Recovery Engine for a single planner entry.
enum RecoveryItemAction {
  /// Keep the entry in today's plan.
  keep,

  /// Move the entry to tomorrow's plan.
  moveToTomorrow,
}

/// A single recommendation line item inside a [RecoveryPlan].
class RecoveryItem {
  final PlannerEntry entry;
  final RecoveryItemAction action;
  final String reason;

  const RecoveryItem({
    required this.entry,
    required this.action,
    required this.reason,
  });

  Map<String, dynamic> toJson() => {
        'entry': entry.toJson(),
        'action': action.name,
        'reason': reason,
      };

  factory RecoveryItem.fromJson(Map<String, dynamic> json) => RecoveryItem(
        entry: PlannerEntry.fromJson(json['entry'] as Map<String, dynamic>),
        action: RecoveryItemAction.values.firstWhere(
          (e) => e.name == json['action'],
          orElse: () => RecoveryItemAction.keep,
        ),
        reason: json['reason'] as String? ?? '',
      );
}

/// Status of the recovery suggestion workflow.
enum RecoveryState {
  /// No recovery suggestion active.
  none,

  /// A recovery suggestion is active and waiting for user input.
  suggested,

  /// User dismissed the suggestion.
  dismissed,

  /// User accepted and applied the suggestion.
  accepted,
}

/// Complete recovery recommendation generated by the Recovery Engine.
class RecoveryPlan {
  final String id;
  final DateTime generatedAt;
  final int remainingWorkloadMinutes;
  final int remainingAvailableMinutes;
  final List<RecoveryItem> items;

  const RecoveryPlan({
    required this.id,
    required this.generatedAt,
    required this.remainingWorkloadMinutes,
    required this.remainingAvailableMinutes,
    required this.items,
  });

  /// Items recommended to be kept today.
  List<RecoveryItem> get keepItems =>
      items.where((i) => i.action == RecoveryItemAction.keep).toList();

  /// Items recommended to be moved to tomorrow.
  List<RecoveryItem> get moveItems =>
      items.where((i) => i.action == RecoveryItemAction.moveToTomorrow).toList();

  Map<String, dynamic> toJson() => {
        'id': id,
        'generatedAt': generatedAt.toIso8601String(),
        'remainingWorkloadMinutes': remainingWorkloadMinutes,
        'remainingAvailableMinutes': remainingAvailableMinutes,
        'items': items.map((i) => i.toJson()).toList(),
      };

  factory RecoveryPlan.fromJson(Map<String, dynamic> json) => RecoveryPlan(
        id: json['id'] as String,
        generatedAt: DateTime.tryParse(json['generatedAt'] as String? ?? '') ??
            DateTime.now(),
        remainingWorkloadMinutes: json['remainingWorkloadMinutes'] as int? ?? 0,
        remainingAvailableMinutes: json['remainingAvailableMinutes'] as int? ?? 0,
        items: (json['items'] as List<dynamic>? ?? [])
            .whereType<Map<String, dynamic>>()
            .map(RecoveryItem.fromJson)
            .toList(),
      );
}
